/**
 * Generated by xport-browser-sdk — do not edit.
 * Source: package.json → xportAutomation (fb-group-post)
 * Regenerate: {BUN} --no-env-file validate.ts
 */
export interface TaskRunConfig {
  host: string;
  content: string;
  post_anonymously: 0 | 1;
  media_type: "image" | "video";
  images?: string[];
  image_count?: number;
  video?: string | null;
}

export interface TaskGroupConfig {
  hosts: string;
  contents: string;
  post_anonymously: 0 | 1;
  media_type: "image" | "video";
  images?: string[];
  image_count?: number;
  videos?: string[];
  browsers: number[];
  daily_limit: number;
  during_min: string;
  during_max: string;
  daily_time_start: string;
  daily_time_end: string;
}

export interface TaskResultData {
  host: string;
  mediaType: string;
  content: string;
  mediaCount: string;
  finalUrl: string;
}
